name: Docker - docker hub

on:
  push:
    branches: [ "v13" ]
  pull_request:
    branches: [ "v13" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag prinkydinky/bot:v13-$(date +%s)

    - name: Docker Push
      run: docker push prinkydinky/bot
